### ISSUE TITLE
Force feedback integration

### ISSUE THREAD

**Issue by danwillm** [LucidVR/opengloves-driver#46]
Integrate a force feedback interface between the driver and games.

Using OpenVR's `IVRIOBuffer` interface is probably the most suitable way to do this, but modding may also be necersarry.

https://github.com/ValveSoftware/openvr/wiki/IVRIOBuffer

**Comment by kitlith** [comment]
it might be worth noting that that wiki page was updated 2 days ago to mark that interface as deprecated

relevant issue: https://github.com/ValveSoftware/openvr/issues/1530

**Comment by danwillm** [comment]
I saw that as well, which is unfortunate. To my knowledge, there's no other way to achieve communication between applications and drivers directly through OpenVR other than that interface, which is a shame.

It would be interesting to know why it was deprecated.

**Comment by kitlith** [comment]
well, perhaps you (or someone else, idk) should go talk to them on that issue (or open a new issue, idk) because they seemed open to going "hey, what do you need it for, we can point you in the right direction and/or work on a new api for it"

if i were more involved/didn't have too many other things on my plate i'd offer to help with that, but i'm not.
